In [1]:
import numpy as np

In [2]:
npa = np.arange(20)

In [3]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
[x for x in npa if x % 2 ==0] 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
filter(lambda x: x % 2 ==0, npa)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
npa % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False], dtype=bool)

In [9]:
npa[npa % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
npa2 = np.arange(20000)

In [14]:
%timeit [x for x in npa2 if x % 2 ==0]

100 loops, best of 3: 8.43 ms per loop


In [15]:
%timeit npa2[npa2 % 2 ==0]

1000 loops, best of 3: 644 µs per loop


In [16]:
npa[npa >10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
npa > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [23]:
(npa > 15) | (npa < 5)

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True], dtype=bool)

In [24]:
npa[(npa > 15) | (npa < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [25]:
np3 = np.array([True for x in range(20)])

In [26]:
np3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [29]:
 print type(npa)

<type 'numpy.ndarray'>


In [31]:
npa.dtype

dtype('int64')

In [32]:
np.array(range(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.array([1.0,2,3,4])

array([ 1.,  2.,  3.,  4.])

In [34]:
np.array([1.0,2,3,4]).dtype

dtype('float64')

In [41]:
npa = np.random.randint(0, 50,20)

In [42]:
npa

array([24, 15,  7, 25, 19, 30,  6, 24, 44, 28, 36, 44, 45, 31, 12, 36, 29,
       46, 30,  1])

In [43]:
map(lambda x: x ** 2, npa)

[576,
 225,
 49,
 625,
 361,
 900,
 36,
 576,
 1936,
 784,
 1296,
 1936,
 2025,
 961,
 144,
 1296,
 841,
 2116,
 900,
 1]

In [44]:
[x ** 2 for x in npa]

[576,
 225,
 49,
 625,
 361,
 900,
 36,
 576,
 1936,
 784,
 1296,
 1936,
 2025,
 961,
 144,
 1296,
 841,
 2116,
 900,
 1]

In [48]:
npa ** 2

array([ 576,  225,   49,  625,  361,  900,   36,  576, 1936,  784, 1296,
       1936, 2025,  961,  144, 1296,  841, 2116,  900,    1])

In [49]:
def new_func(num):
    if num < 10: 
        return num ** 3
    else: 
        return num ** 2


In [50]:
new_func(npa)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
np.vectorize?

In [52]:
vnew_func = np.vectorize(new_func)

In [53]:
vnew_func(npa)

array([ 576,  225,  343,  625,  361,  900,  216,  576, 1936,  784, 1296,
       1936, 2025,  961,  144, 1296,  841, 2116,  900,    1])

In [54]:
type(vnew_func)

numpy.lib.function_base.vectorize

In [55]:
[new_func(x) for x in npa]

[576,
 225,
 343,
 625,
 361,
 900,
 216,
 576,
 1936,
 784,
 1296,
 1936,
 2025,
 961,
 144,
 1296,
 841,
 2116,
 900,
 1]

In [56]:
 npa

array([24, 15,  7, 25, 19, 30,  6, 24, 44, 28, 36, 44, 45, 31, 12, 36, 29,
       46, 30,  1])

In [61]:
npa = np.arange(25)

In [62]:
npa.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])